### ISSUE TITLE
SyntaxError: Unexpected token ;

### ISSUE THREAD

**Issue by jcobreros** [minosvasilias/toolformer-zero#4]
I'm getting:

SyntaxError: Unexpected token ; in /home/userX/toolformer-zero/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;

 SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jesus/toolformer-zero/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    
    
  I just followed the instructions: Clone, run npm install with no issues, and I get this error when running npm start

**Comment by minosvasilias** [comment]
Hey! 
Searching around for this jest error it seems like bumping up your Node version might resolve this. [^1]
Minimum expected Node version for this project would be `16.18`.

[^1]: https://answers.netlify.com/t/react-app-doesnt-deploy-via-git-repo-but-does-with-netlify-cli/73700/11

**Comment by minosvasilias** [comment]
Closing this for now due to no indication on whether or not this was resolved.
Testing initialization of the project on fresh environments did work for me though.
